name = "{{WORKER_NAME}}"
main = "./worker.js"
compatibility_date = "2025-07-01"

{{R2_ROUTES}}

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "{{BUCKET_NAME}}"

[vars]
R2_PATHS = '{{R2_PATHS_JSON}}'
